print("SJC23MCA-2047 : SANDRA SAJI")
print("Batch : MCA 2023-25")
import numpy as np
matrix_size = 3
matrix = np.random.randint(10,20, size=(matrix_size, matrix_size))
print("Original matrix:")
print(matrix)
if np.linalg.matrix_rank(matrix) == matrix_size:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse matrix:")
    print(inverse_matrix)
else:
    print("\nThe matrix is not invertible (its rank is less than the size).")
    rank =  np.linalg.matrix_rank(matrix)
    print("\nRank of the matrix:",rank)
    determinant = np.linalg.det(matrix)
    print("\nDeterminant of the matrix:", determinant)
    matrix_1d = matrix.flatten()
    print("\nMatrix as 1D array:")
    print(matrix_1d)
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    print("\nEigenvalues:")
    print(eigenvalues)
    print("\nEigenvectors:")
    print(eigenvectors)
